HARD_GREEN_BLOCKERS = {
    "SCHEMA_INVALID",
    "MISSING_ASSIGNED_CONTENT",
    "DUPLICATE_ITEM",
    "NUMBERING_CONFLICT",
    "CRITICAL_SYMBOL_MISMATCH",
    "MARK_TOTAL_MISMATCH",
    "QUESTION_TOTAL_MISMATCH",
    "DOCUMENT_TOTAL_MISMATCH",
    "UNRESOLVED_SOURCE_CONTRADICTION",
    "UNCONFIRMED_CORRECTION",
    "MISSING_REQUIRED_ASSET",
    "GLYPH_PREFLIGHT_FAILED",
}
